export type FaxStatus = "unconfirmed" | "confirmed" | "finalized"

export interface FaxItem {
  id: number
  dateTime: string
  tradingPartner: string
  siteName: string
  status: FaxStatus
  housemaker: string
  address: string
  contactName: string
  contactPhone: string
  notes: string
  workContent: string
  nearestStation: string
  walkingDistance: string
  workers: string
  transportCost: string
}

export type FaxFormData = Omit<FaxItem, "id" | "status">

export function faxToFormData(fax: FaxItem): FaxFormData {
  return {
    dateTime: fax.dateTime,
    tradingPartner: fax.tradingPartner,
    siteName: fax.siteName,
    housemaker: fax.housemaker,
    address: fax.address,
    contactName: fax.contactName,
    contactPhone: fax.contactPhone,
    notes: fax.notes,
    workContent: fax.workContent,
    nearestStation: fax.nearestStation,
    walkingDistance: fax.walkingDistance,
    workers: fax.workers,
    transportCost: fax.transportCost,
  }
}

export const dummyFaxList: FaxItem[] = [
  {
    id: 1,
    dateTime: "2026-01-15T09:00",
    tradingPartner: "ジューテック開発2",
    siteName: "ライオンズマンション麹町501",
    status: "unconfirmed",
    housemaker: "朝日・マンション住替センター",
    address: "千代田区麹町2-5-3",
    contactName: "前田",
    contactPhone: "070-3277-6870",
    notes: "※挨拶やマナー等しっかりと、注意事項沢山ありますのでご注意下さい\n※動力の方は邪魔にならない所へ仮停車し、管理人室へ停車可能場所を確認する事\n※共用部への仮置きは極力控え、やむを得ず置く場合は養生をする等十分に注意する事",
    workContent: "【2F外階段3段の内右：0331】\nシステムキッチン一式の搬入(職方様不在、運転手と作業開始して下さい)\nトラック到着：9：20～9：40\n※安全靴・上履き着用の事!\n※現場及び現場周辺（路上含む）は禁煙",
    nearestStation: "半蔵門駅",
    walkingDistance: "110",
    workers: "4名ハーフ作業",
    transportCost: "5000",
  },
  {
    id: 2,
    dateTime: "2026-01-15T11:00",
    tradingPartner: "加藤ベニヤ本社",
    siteName: "新井　彰 邸",
    status: "unconfirmed",
    housemaker: "ミサワホーム",
    address: "目黒区八雲1-10-8付近",
    contactName: "向井監督",
    contactPhone: "090-3230-3347",
    notes: "※安全靴・上履き着用の事!\n※タオル巻き禁止!\n※現場内及び周辺(路上含む)は禁煙",
    workContent: "（外差し）\n12　3×6　1F37　2F45\n強12　3×6　3F4\n強15　3×8　1F10　2F10　3F10\nバリア強12　3×6　1F3　2F3\nバリア強15　3×8　1F1\nSH12　3×6　2F21　3F22\n　合計　166枚",
    nearestStation: "都立大学",
    walkingDistance: "500",
    workers: "4名ハーフ作業",
    transportCost: "4500",
  },
  {
    id: 3,
    dateTime: "2026-01-15T13:00",
    tradingPartner: "加藤ベニヤ本社",
    siteName: "大田区西蒲田301②　2号棟",
    status: "unconfirmed",
    housemaker: "ホークワン",
    address: "大田区西蒲田3-1-7",
    contactName: "竹村監督",
    contactPhone: "080-5544-1263",
    notes: "※作業前、作業後に必ず入場者名簿を記入!(記入モレは戻ってもらう事になります)\n※建物内土足厳禁\n※角欠けや破損に注意!(以前ご指摘あり)\n※安全靴・上履き着用の事!\n※タオル巻き禁止!\n※現場内及び周辺(路上含む)は禁煙",
    workContent: "(3F建・2TS現場・キーBOX№5741)\n15　3×9　1F40　2F50　3F63\n強15　3×6　1F14　2F25　3F21\n　合計　213枚",
    nearestStation: "蓮沼駅",
    walkingDistance: "830",
    workers: "3名ハーフ作業",
    transportCost: "4000",
  },
  {
    id: 4,
    dateTime: "2026-01-14T15:30",
    tradingPartner: "ジューテック開発2",
    siteName: "品川区南大井マンション",
    status: "confirmed",
    housemaker: "住友不動産",
    address: "品川区南大井4-5-6",
    contactName: "山田",
    contactPhone: "03-1234-5678",
    notes: "※エレベーター使用可\n※駐車場あり",
    workContent: "システムバス搬入",
    nearestStation: "大森駅",
    walkingDistance: "300",
    workers: "3名作業",
    transportCost: "3500",
  },
  {
    id: 5,
    dateTime: "2026-01-14T17:00",
    tradingPartner: "東京建材",
    siteName: "世田谷区上野毛邸",
    status: "finalized",
    housemaker: "積水ハウス",
    address: "世田谷区上野毛2-3-4",
    contactName: "佐藤",
    contactPhone: "090-9876-5432",
    notes: "※静かに作業すること",
    workContent: "フローリング材搬入\n合計 50枚",
    nearestStation: "上野毛駅",
    walkingDistance: "200",
    workers: "2名作業",
    transportCost: "3000",
  },
  {
    id: 6,
    dateTime: "2026-01-14T10:00",
    tradingPartner: "日本建材",
    siteName: "港区芝公園ビル",
    status: "unconfirmed",
    housemaker: "大成建設",
    address: "港区芝公園1-2-3",
    contactName: "田中",
    contactPhone: "03-5555-1234",
    notes: "※セキュリティカード必要",
    workContent: "建材搬入一式",
    nearestStation: "芝公園駅",
    walkingDistance: "150",
    workers: "4名作業",
    transportCost: "4200",
  },
  {
    id: 7,
    dateTime: "2026-01-13T09:00",
    tradingPartner: "ジューテック開発2",
    siteName: "渋谷区恵比寿マンション",
    status: "finalized",
    housemaker: "野村不動産",
    address: "渋谷区恵比寿1-2-3",
    contactName: "高橋",
    contactPhone: "03-4444-5555",
    notes: "",
    workContent: "キッチン設備搬入",
    nearestStation: "恵比寿駅",
    walkingDistance: "400",
    workers: "3名作業",
    transportCost: "3800",
  },
  {
    id: 8,
    dateTime: "2026-01-13T14:00",
    tradingPartner: "加藤ベニヤ本社",
    siteName: "新宿区西新宿ビル",
    status: "confirmed",
    housemaker: "清水建設",
    address: "新宿区西新宿6-7-8",
    contactName: "伊藤",
    contactPhone: "03-6666-7777",
    notes: "※地下駐車場使用可",
    workContent: "内装材搬入",
    nearestStation: "西新宿駅",
    walkingDistance: "250",
    workers: "5名作業",
    transportCost: "4000",
  },
  {
    id: 9,
    dateTime: "2026-01-12T11:00",
    tradingPartner: "東京建材",
    siteName: "中央区銀座オフィス",
    status: "finalized",
    housemaker: "鹿島建設",
    address: "中央区銀座3-4-5",
    contactName: "渡辺",
    contactPhone: "03-7777-8888",
    notes: "※搬入口は裏手",
    workContent: "OAフロア材搬入",
    nearestStation: "銀座駅",
    walkingDistance: "100",
    workers: "4名作業",
    transportCost: "5500",
  },
  {
    id: 10,
    dateTime: "2026-01-12T16:00",
    tradingPartner: "日本建材",
    siteName: "豊島区池袋マンション",
    status: "unconfirmed",
    housemaker: "三井不動産",
    address: "豊島区池袋2-3-4",
    contactName: "小林",
    contactPhone: "03-8888-9999",
    notes: "※夜間作業禁止",
    workContent: "床材搬入\n合計 80枚",
    nearestStation: "池袋駅",
    walkingDistance: "350",
    workers: "3名作業",
    transportCost: "3200",
  },
  {
    id: 11,
    dateTime: "2026-01-11T09:30",
    tradingPartner: "ジューテック開発2",
    siteName: "文京区本郷邸",
    status: "confirmed",
    housemaker: "住友林業",
    address: "文京区本郷5-6-7",
    contactName: "加藤",
    contactPhone: "03-1111-2222",
    notes: "",
    workContent: "木材搬入",
    nearestStation: "本郷三丁目駅",
    walkingDistance: "180",
    workers: "2名作業",
    transportCost: "2800",
  },
  {
    id: 12,
    dateTime: "2026-01-11T13:00",
    tradingPartner: "加藤ベニヤ本社",
    siteName: "台東区上野ビル",
    status: "unconfirmed",
    housemaker: "大林組",
    address: "台東区上野1-2-3",
    contactName: "斎藤",
    contactPhone: "03-2222-3333",
    notes: "※荷物用エレベーター使用",
    workContent: "建材一式搬入",
    nearestStation: "上野駅",
    walkingDistance: "220",
    workers: "4名作業",
    transportCost: "3600",
  },
  {
    id: 13,
    dateTime: "2026-01-10T10:00",
    tradingPartner: "東京建材",
    siteName: "墨田区錦糸町マンション",
    status: "finalized",
    housemaker: "東急不動産",
    address: "墨田区錦糸4-5-6",
    contactName: "松本",
    contactPhone: "03-3333-4444",
    notes: "",
    workContent: "フローリング搬入",
    nearestStation: "錦糸町駅",
    walkingDistance: "280",
    workers: "3名作業",
    transportCost: "3400",
  },
  {
    id: 14,
    dateTime: "2026-01-10T15:00",
    tradingPartner: "日本建材",
    siteName: "江東区豊洲タワー",
    status: "confirmed",
    housemaker: "三菱地所",
    address: "江東区豊洲3-4-5",
    contactName: "井上",
    contactPhone: "03-4444-5555",
    notes: "※タワー駐車場利用可",
    workContent: "内装建材搬入",
    nearestStation: "豊洲駅",
    walkingDistance: "150",
    workers: "5名作業",
    transportCost: "4800",
  },
  {
    id: 15,
    dateTime: "2026-01-09T11:00",
    tradingPartner: "ジューテック開発2",
    siteName: "杉並区荻窪邸",
    status: "unconfirmed",
    housemaker: "パナソニックホームズ",
    address: "杉並区荻窪2-3-4",
    contactName: "木村",
    contactPhone: "03-5555-6666",
    notes: "※住宅街のため静かに",
    workContent: "システムキッチン搬入",
    nearestStation: "荻窪駅",
    walkingDistance: "400",
    workers: "3名作業",
    transportCost: "3900",
  },
]
