export type ReportStatus = "未確認" | "確認済み" | "差異あり"

export interface SiteReport {
  id: string
  reportedAt: string       // 報告日時 e.g. "2026/02/24 21:23"
  workerName: string       // 作業員名
  workDate: string         // 現場日付 e.g. "2/24"
  orderNumber: string      // 手配番号
  clientName: string       // 顧客名(略称)
  siteName: string         // 現場名
  startTime: string        // 開始時刻
  endTime: string          // 終了時刻
  duration: string         // 作業時間
  witness: string          // 立会者
  notes: string            // 備考
  status: ReportStatus
  // Detail panel fields
  clientFullName: string
  siteAddress: string
  gcHm: string
  workCategory: string
  plannedWorkers: number
  planned: {
    workDate: string
    startTime: string
    endTime: string
    duration: string
  }
  actual: {
    workDate: string
    startTime: string
    endTime: string
    duration: string
    witnessCategory: string
    witnessName: string
  }
  fullNotes: string
  hasPhotos: boolean
}

export const SAMPLE_REPORTS: SiteReport[] = [
  {
    id: "r-001",
    reportedAt: "2026/02/24 21:23",
    workerName: "古市 英佑",
    workDate: "2/24",
    orderNumber: "26-004521",
    clientName: "ミロク東京",
    siteName: "尾﨑 洋子・裕美 邸",
    startTime: "13:30",
    endTime: "14:30",
    duration: "1.0h",
    witness: "大工・辻さん",
    notes: "",
    status: "未確認",
    clientFullName: "ミロク商事株式会社 東京支店",
    siteAddress: "東京都世田谷区上北沢3-4-2",
    gcHm: "ハウスメーカー1",
    workCategory: "フル作業",
    plannedWorkers: 2,
    planned: { workDate: "2026/02/24", startTime: "13:00", endTime: "15:00", duration: "2.0h" },
    actual: { workDate: "2026/02/24", startTime: "13:30", endTime: "14:30", duration: "1.0h", witnessCategory: "大工", witnessName: "辻さん" },
    fullNotes: "",
    hasPhotos: false,
  },
  {
    id: "r-002",
    reportedAt: "2026/02/24 21:22",
    workerName: "古市 英佑",
    workDate: "2/21",
    orderNumber: "26-004498",
    clientName: "ミロク東京",
    siteName: "加瀬 典之・けい子 邸",
    startTime: "16:00",
    endTime: "17:00",
    duration: "1.0h",
    witness: "大工・山口さん",
    notes: "",
    status: "未確認",
    clientFullName: "ミロク商事株式会社 東京支店",
    siteAddress: "東京都練馬区関町北4-12-7",
    gcHm: "ハウスメーカー1",
    workCategory: "フル作業",
    plannedWorkers: 2,
    planned: { workDate: "2026/02/21", startTime: "16:00", endTime: "17:00", duration: "1.0h" },
    actual: { workDate: "2026/02/21", startTime: "16:00", endTime: "17:00", duration: "1.0h", witnessCategory: "大工", witnessName: "山口さん" },
    fullNotes: "",
    hasPhotos: false,
  },
  {
    id: "r-003",
    reportedAt: "2026/02/24 20:45",
    workerName: "鈴木 大地",
    workDate: "2/24",
    orderNumber: "26-004519",
    clientName: "住友林業",
    siteName: "渡辺 健一 邸",
    startTime: "09:00",
    endTime: "11:30",
    duration: "2.5h",
    witness: "監督・佐々木さん",
    notes: "2F搬入、階段狭く要注意",
    status: "確認済み",
    clientFullName: "住友林業株式会社",
    siteAddress: "東京都杉並区善福寺2-8-15",
    gcHm: "住友林業",
    workCategory: "フル作業",
    plannedWorkers: 3,
    planned: { workDate: "2026/02/24", startTime: "09:00", endTime: "11:30", duration: "2.5h" },
    actual: { workDate: "2026/02/24", startTime: "09:00", endTime: "11:30", duration: "2.5h", witnessCategory: "監督", witnessName: "佐々木さん" },
    fullNotes: "2F搬入、階段狭く要注意。養生必須。",
    hasPhotos: false,
  },
  {
    id: "r-004",
    reportedAt: "2026/02/24 20:30",
    workerName: "鈴木 大地",
    workDate: "2/24",
    orderNumber: "26-004520",
    clientName: "積水ハウス",
    siteName: "小林 修 邸",
    startTime: "13:00",
    endTime: "15:00",
    duration: "2.0h",
    witness: "大工・田村さん",
    notes: "",
    status: "確認済み",
    clientFullName: "積水ハウス株式会社",
    siteAddress: "東京都板橋区高島平3-11-6",
    gcHm: "積水ハウス",
    workCategory: "ハーフ作業",
    plannedWorkers: 2,
    planned: { workDate: "2026/02/24", startTime: "13:00", endTime: "15:00", duration: "2.0h" },
    actual: { workDate: "2026/02/24", startTime: "13:00", endTime: "15:00", duration: "2.0h", witnessCategory: "大工", witnessName: "田村さん" },
    fullNotes: "",
    hasPhotos: false,
  },
  {
    id: "r-005",
    reportedAt: "2026/02/24 20:15",
    workerName: "佐藤 翔太",
    workDate: "2/24",
    orderNumber: "26-004515",
    clientName: "大和ハウス",
    siteName: "高橋 美咲 邸",
    startTime: "08:30",
    endTime: "10:00",
    duration: "1.5h",
    witness: "施主・高橋様",
    notes: "施主立会い、丁寧搬入",
    status: "確認済み",
    clientFullName: "大和ハウス工業株式会社",
    siteAddress: "東京都目黒区八雲2-5-10",
    gcHm: "大和ハウス",
    workCategory: "フル作業",
    plannedWorkers: 2,
    planned: { workDate: "2026/02/24", startTime: "08:30", endTime: "10:00", duration: "1.5h" },
    actual: { workDate: "2026/02/24", startTime: "08:30", endTime: "10:00", duration: "1.5h", witnessCategory: "施主", witnessName: "高橋様" },
    fullNotes: "施主立会い、丁寧搬入。特に問題なし。",
    hasPhotos: false,
  },
  {
    id: "r-006",
    reportedAt: "2026/02/24 20:10",
    workerName: "佐藤 翔太",
    workDate: "2/24",
    orderNumber: "26-004516",
    clientName: "ミロク東京",
    siteName: "中村 誠一 邸",
    startTime: "11:00",
    endTime: "12:30",
    duration: "1.5h",
    witness: "大工・木村さん",
    notes: "",
    status: "未確認",
    clientFullName: "ミロク商事株式会社 東京支店",
    siteAddress: "東京都中野区本町4-22-3",
    gcHm: "ハウスメーカー1",
    workCategory: "フル作業",
    plannedWorkers: 2,
    planned: { workDate: "2026/02/24", startTime: "11:00", endTime: "12:30", duration: "1.5h" },
    actual: { workDate: "2026/02/24", startTime: "11:00", endTime: "12:30", duration: "1.5h", witnessCategory: "大工", witnessName: "木村さん" },
    fullNotes: "",
    hasPhotos: false,
  },
  {
    id: "r-007",
    reportedAt: "2026/02/24 19:50",
    workerName: "田村 拓也",
    workDate: "2/24",
    orderNumber: "26-004512",
    clientName: "一条工務店",
    siteName: "山田 太郎 邸",
    startTime: "09:00",
    endTime: "10:30",
    duration: "1.5h",
    witness: "大工・伊藤さん",
    notes: "資材一部破損、写真あり",
    status: "差異あり",
    clientFullName: "株式会社一条工務店",
    siteAddress: "東京都足立区千住大川町5-3",
    gcHm: "一条工務店",
    workCategory: "フル作業",
    plannedWorkers: 3,
    planned: { workDate: "2026/02/24", startTime: "08:30", endTime: "10:30", duration: "2.0h" },
    actual: { workDate: "2026/02/24", startTime: "09:00", endTime: "10:30", duration: "1.5h", witnessCategory: "大工", witnessName: "伊藤さん" },
    fullNotes: "資材一部破損（石膏ボード3枚）、写真あり。搬入時に階段で角をぶつけた模様。顧客には報告済み。",
    hasPhotos: true,
  },
  {
    id: "r-008",
    reportedAt: "2026/02/24 19:45",
    workerName: "田村 拓也",
    workDate: "2/24",
    orderNumber: "26-004513",
    clientName: "住友林業",
    siteName: "井上 和子 邸",
    startTime: "14:00",
    endTime: "16:00",
    duration: "2.0h",
    witness: "監督・中島さん",
    notes: "",
    status: "未確認",
    clientFullName: "住友林業株式会社",
    siteAddress: "東京都練馬区石神井台7-1-8",
    gcHm: "住友林業",
    workCategory: "フル作業",
    plannedWorkers: 2,
    planned: { workDate: "2026/02/24", startTime: "14:00", endTime: "16:00", duration: "2.0h" },
    actual: { workDate: "2026/02/24", startTime: "14:00", endTime: "16:00", duration: "2.0h", witnessCategory: "監督", witnessName: "中島さん" },
    fullNotes: "",
    hasPhotos: false,
  },
  {
    id: "r-009",
    reportedAt: "2026/02/24 19:30",
    workerName: "山本 健太",
    workDate: "2/24",
    orderNumber: "26-004510",
    clientName: "セキスイハイム",
    siteName: "松本 裕子 邸",
    startTime: "08:00",
    endTime: "09:30",
    duration: "1.5h",
    witness: "大工・石川さん",
    notes: "",
    status: "確認済み",
    clientFullName: "セキスイハイム株式会社",
    siteAddress: "東京都北区赤羽南1-20-4",
    gcHm: "セキスイハイム",
    workCategory: "ハーフ作業",
    plannedWorkers: 2,
    planned: { workDate: "2026/02/24", startTime: "08:00", endTime: "09:30", duration: "1.5h" },
    actual: { workDate: "2026/02/24", startTime: "08:00", endTime: "09:30", duration: "1.5h", witnessCategory: "大工", witnessName: "石川さん" },
    fullNotes: "",
    hasPhotos: false,
  },
  {
    id: "r-010",
    reportedAt: "2026/02/24 19:20",
    workerName: "山本 健太",
    workDate: "2/24",
    orderNumber: "26-004511",
    clientName: "大和ハウス",
    siteName: "藤田 正義 邸",
    startTime: "10:30",
    endTime: "12:00",
    duration: "1.5h",
    witness: "大工・清水さん",
    notes: "予定より30分超過（渋滞）",
    status: "差異あり",
    clientFullName: "大和ハウス工業株式会社",
    siteAddress: "東京都豊島区南長崎4-8-12",
    gcHm: "大和ハウス",
    workCategory: "フル作業",
    plannedWorkers: 2,
    planned: { workDate: "2026/02/24", startTime: "10:00", endTime: "11:30", duration: "1.5h" },
    actual: { workDate: "2026/02/24", startTime: "10:30", endTime: "12:00", duration: "1.5h", witnessCategory: "大工", witnessName: "清水さん" },
    fullNotes: "予定より30分超過（渋滞による遅延）。作業自体は問題なく完了。",
    hasPhotos: false,
  },
  {
    id: "r-011",
    reportedAt: "2026/02/24 18:55",
    workerName: "古市 英佑",
    workDate: "2/24",
    orderNumber: "26-004508",
    clientName: "積水ハウス",
    siteName: "岡田 幸一 邸",
    startTime: "09:00",
    endTime: "11:00",
    duration: "2.0h",
    witness: "大工・原田さん",
    notes: "",
    status: "未確認",
    clientFullName: "積水ハウス株式会社",
    siteAddress: "東京都世田谷区成城6-14-2",
    gcHm: "積水ハウス",
    workCategory: "フル作業",
    plannedWorkers: 3,
    planned: { workDate: "2026/02/24", startTime: "09:00", endTime: "11:00", duration: "2.0h" },
    actual: { workDate: "2026/02/24", startTime: "09:00", endTime: "11:00", duration: "2.0h", witnessCategory: "大工", witnessName: "原田さん" },
    fullNotes: "",
    hasPhotos: false,
  },
  {
    id: "r-012",
    reportedAt: "2026/02/24 18:40",
    workerName: "中島 翼",
    workDate: "2/24",
    orderNumber: "26-004506",
    clientName: "ミサワホーム",
    siteName: "西村 雅彦 邸",
    startTime: "08:30",
    endTime: "10:30",
    duration: "2.0h",
    witness: "大工・松田さん",
    notes: "",
    status: "確認済み",
    clientFullName: "ミサワホーム株式会社",
    siteAddress: "東京都大田区田園調布3-25-8",
    gcHm: "ミサワホーム",
    workCategory: "フル作業",
    plannedWorkers: 2,
    planned: { workDate: "2026/02/24", startTime: "08:30", endTime: "10:30", duration: "2.0h" },
    actual: { workDate: "2026/02/24", startTime: "08:30", endTime: "10:30", duration: "2.0h", witnessCategory: "大工", witnessName: "松田さん" },
    fullNotes: "",
    hasPhotos: false,
  },
]
